=== patrodyne/hisrc-higherjaxb/tests/dtd/checkbook/src/main/resources/CheckBook.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT name (#PCDATA) >
<!ELEMENT memo (#PCDATA) >

<!ELEMENT cleared EMPTY >
<!ELEMENT pending EMPTY >
<!ELEMENT void EMPTY >

<!ELEMENT amount EMPTY >
<!ATTLIST amount
          value CDATA #REQUIRED >

<!ELEMENT balance EMPTY >
<!ATTLIST balance
          value CDATA #REQUIRED >

<!ELEMENT date EMPTY >
<!ATTLIST date
          value CDATA #REQUIRED >

<!ELEMENT checkbook ( transactions, balance ) >

<!ELEMENT deposit ( date, name, amount )>
<!ATTLIST deposit category ( salary | interest-income | other ) #IMPLIED >

<!ELEMENT check ( date, name, amount, ( pending | void | cleared ), memo? ) >
<!ATTLIST check number CDATA #REQUIRED category ( rent | groceries | other ) #IMPLIED >

<!ELEMENT withdrawal ( date, amount ) >

<!ELEMENT transactions ( deposit | check | withdrawal )* >

<!ELEMENT something ( date ) >

=== patrodyne/hisrc-higherjaxb/tests/dtd/checkbook/src/test/samples/Transactions-200103A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<!DOCTYPE transactions SYSTEM "../../main/resources/CheckBook.dtd">
 -->
<transactions>

	<check number="2" category="groceries">
		<date value="03-15-2001"/>
		<name>Conglomerate Foods</name>
		<amount value="34.95"/>
		<pending/>
		<memo>food</memo>
	</check>

	<withdrawal>
		<date value="03-16-2001"/>
		<amount value="0.34"/>
	</withdrawal>

</transactions>
