=== patrodyne/hisrc-higherjaxb/w3c/xmlschema-v1_0/src/test/resources/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	elementFormDefault="qualified"
	targetNamespace="urn:po"
	xmlns:po="urn:po"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
>

	<!-- Stock Keeping Unit, a code for identifying products -->
	<xsd:simpleType name="SKU">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{3}-[A-Z]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Credit">
		<xsd:attribute name="amount" type="xsd:double"></xsd:attribute>
		<xsd:attribute name="reason" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="USAddress">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="street" type="xsd:string"/>
			<xsd:element name="city" type="xsd:string"/>
			<xsd:element name="state" type="xsd:string"/>
			<xsd:element name="zip" type="xsd:decimal"/>
		</xsd:sequence>
		<xsd:attribute name="country" type="xsd:NMTOKEN" fixed="US"/>
	</xsd:complexType>

	<xsd:complexType name="Items">
		<xsd:sequence>
			<xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="productName" type="xsd:string"/>
						<xsd:element name="quantity">
							<xsd:simpleType>
								<xsd:restriction base="xsd:positiveInteger">
									<xsd:maxExclusive value="100"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="USPrice" type="xsd:decimal"/>
						<xsd:element ref="po:comment" minOccurs="0"/>
						<xsd:element name="shipDate" type="xsd:date" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="partNum" type="po:SKU" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="comment" type="xsd:string"/>

	<!-- Top element(s) with anonymous complex type become XmlRootElement(s). -->
	<xsd:element name="purchaseOrder">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="shipTo" type="po:USAddress" />
				<xsd:element name="billTo" type="po:USAddress" />
				<xsd:element ref="po:comment" minOccurs="0" />
				<xsd:element name="items" type="po:Items" />
				<xsd:element name="payments">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="payment" maxOccurs="unbounded" minOccurs="0">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:decimal">
											<xsd:attribute name="paymentDate" type="xsd:date" />
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="credits" type="po:Credit" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="orderDate" type="xsd:date" />
			<xsd:attribute name="complete" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Purchase order schema for Example.com.
			Copyright 2000 Example.com. All rights reserved.
		</xsd:documentation>
	</xsd:annotation>

</xsd:schema>
<!-- vi:set tabstop=4 hardtabs=4 shiftwidth=4: -->

=== patrodyne/hisrc-higherjaxb/w3c/xmlschema-v1_0/src/test/samples/po.xml
<purchaseOrder orderDate="1999-05-20" complete="false"
	xmlns="urn:po"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:po ../resources/po.xsd"
    
>
  <shipTo country="US">
    <name>Alice Smith</name>
    <street>123 Maple Street</street>
    <city>Mill Valley</city>
    <state>CA</state>
    <zip>90952</zip>
  </shipTo>
  <billTo country="US">
    <name>Robert Smith</name>
    <street>8 Oak Avenue</street>
    <city>Old Town</city>
    <state>PA</state>
    <zip>95819</zip>
  </billTo>
  <comment>Hurry, my lawn is going wild!</comment>
  <items>
    <item partNum="872-AA">
      <productName>Lawnmower</productName>
      <quantity>1</quantity>
      <USPrice>148.95</USPrice>
      <comment>Confirm this is electric</comment>
    </item>
    <item partNum="926-AA">
      <productName>Baby Monitor</productName>
      <quantity>1</quantity>
      <USPrice>39.98</USPrice>
      <shipDate>1999-10-21</shipDate>
    </item>
  </items>
  <payments>
    <payment paymentDate="1999-10-21">5.00</payment>
    <payment paymentDate="1999-10-22">10.00</payment>
    <payment paymentDate="1999-10-23">24.98</payment>
  </payments>
  <credits amount="5.00" reason="Promo: MAY99" />
  <credits amount="10.00" reason="Promo: OCT99" />
</purchaseOrder>
