=== patrodyne/hisrc-higherjaxb/tests/dtd/book/src/main/resources/Book.dtd
<?xml encoding="UTF-8"?>

<!--
<!ELEMENT book (title, author, chapter+) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA)>
<!ELEMENT chapter (#PCDATA) >
-->

<!--
<!ELEMENT book (title, author, (prologue | preface), chapter+) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA)>
<!ELEMENT prologue (#PCDATA) >
<!ELEMENT preface (#PCDATA) >
<!ELEMENT chapter (#PCDATA) >
-->

<!ELEMENT book (titlepage, (prologue | preface), toc, chapter+, epilogue?, appendix*) >
<!ATTLIST book type ( fiction | travel | history | biography ) #REQUIRED >

<!ELEMENT titlepage (title, author) >
<!ELEMENT prologue (#PCDATA) >
<!ELEMENT preface (#PCDATA) >
<!ELEMENT toc (chaptitle+, appendixtitle*) >
<!ELEMENT chaptitle (#PCDATA) >
<!ELEMENT appendixtitle (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA)>
<!ELEMENT chapter (chaptitle, body) >
<!ELEMENT body (#PCDATA) >
<!ELEMENT epilogue (#PCDATA) >
<!ELEMENT appendix (appendixtitle, body) >

=== patrodyne/hisrc-higherjaxb/tests/dtd/book/src/test/samples/Book01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "../../main/resources/Book.dtd">
<book type="biography">
  <titlepage>
    <title>Duke: My Life and Times</title>
    <author>Duke</author>
  </titlepage>
  <prologue>I dedicate this book to ...</prologue>
  <toc>
    <chaptitle>The Early Years</chaptitle>
    <chaptitle>The Later Years</chaptitle>
  </toc>
  <chapter>
    <chaptitle>The Early Years</chaptitle>
    <body>Blah blah blah</body>
  </chapter>
  <chapter>
    <chaptitle>The Later Years</chaptitle>
    <body>Blah blah</body>
  </chapter>
</book>
