=== patrodyne/hisrc-higherjaxb/tests/nothing/src/main/resources/nothing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	jaxb:version="3.0"
	xmlns:tns="urn:example.org:nothing"
	targetNamespace="urn:example.org:nothing"
>
	<xs:element name="Nothing">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="optionalNillableString" type="xs:string" minOccurs="0" nillable="true"/>
				<xs:element name="requiredNillableString" type="xs:string" minOccurs="1" nillable="true"/>
				<xs:element name="optionalNillableStrings" type="xs:string" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
				<xs:element name="requiredNillableStrings" type="xs:string" minOccurs="1" maxOccurs="unbounded" nillable="true"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:int" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Nothings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:Nothing" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		
</xs:schema>

=== patrodyne/hisrc-higherjaxb/tests/nothing/src/test/samples/nothings01.xml
<?xml version="1.0" encoding="UTF-8"?>
<no:Nothings
	xmlns:no="urn:example.org:nothing"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:example.org:nothing ../../main/resources/nothing.xsd"
>
	<no:Nothing id="101">
		<optionalNillableString xsi:nil="true"/>
		<requiredNillableString xsi:nil="true"/>
		<optionalNillableStrings xsi:nil="true"/>
		<optionalNillableStrings xsi:nil="true"/>
		<requiredNillableStrings xsi:nil="true"/>
		<requiredNillableStrings xsi:nil="true"/>
	</no:Nothing>
	<no:Nothing id="102">
		<optionalNillableString xsi:nil="false"/>
		<requiredNillableString xsi:nil="false"/>
		<optionalNillableStrings xsi:nil="false"/>
		<optionalNillableStrings xsi:nil="false"/>
		<requiredNillableStrings xsi:nil="false"/>
		<requiredNillableStrings xsi:nil="false"/>
	</no:Nothing>
	<no:Nothing id="103">
		<optionalNillableString/>
		<requiredNillableString/>
		<optionalNillableStrings/>
		<optionalNillableStrings/>
		<requiredNillableStrings/>
		<requiredNillableStrings/>
	</no:Nothing>
	<no:Nothing id="104">
		<requiredNillableString/>
		<requiredNillableStrings/>
	</no:Nothing>
	<no:Nothing id="105">
		<optionalNillableString>ONS01</optionalNillableString>
		<requiredNillableString>RNS01</requiredNillableString>
		<optionalNillableStrings>ONSS01</optionalNillableStrings>
		<optionalNillableStrings>ONSS02</optionalNillableStrings>
		<optionalNillableStrings xsi:nil="true"/>
		<optionalNillableStrings xsi:nil="false"/>
		<requiredNillableStrings>RNSS01</requiredNillableStrings>
		<requiredNillableStrings>RNSS02</requiredNillableStrings>
		<requiredNillableStrings xsi:nil="true"/>
		<requiredNillableStrings xsi:nil="false"/>
	</no:Nothing>
</no:Nothings>
